/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthResetRouteImport } from './routes/auth.reset'
import { Route as AuthForgotRouteImport } from './routes/auth.forgot'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppProfileIndexRouteImport } from './routes/_app.profile.index'
import { Route as AppCustomersIndexRouteImport } from './routes/_app.customers.index'
import { Route as AppProfileChangePasswordRouteImport } from './routes/_app.profile.change-password'
import { Route as AppCustomersNewRouteImport } from './routes/_app.customers.new'
import { Route as AppCustomersIdIndexRouteImport } from './routes/_app.customers.$id.index'
import { Route as AppCustomersIdEditRouteImport } from './routes/_app.customers.$id.edit'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetRoute = AuthResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotRoute = AuthForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => AuthRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileIndexRoute = AppProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersIndexRoute = AppCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileChangePasswordRoute =
  AppProfileChangePasswordRouteImport.update({
    id: '/profile/change-password',
    path: '/profile/change-password',
    getParentRoute: () => AppRoute,
  } as any)
const AppCustomersNewRoute = AppCustomersNewRouteImport.update({
  id: '/customers/new',
  path: '/customers/new',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersIdIndexRoute = AppCustomersIdIndexRouteImport.update({
  id: '/customers/$id/',
  path: '/customers/$id/',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersIdEditRoute = AppCustomersIdEditRouteImport.update({
  id: '/customers/$id/edit',
  path: '/customers/$id/edit',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/reset': typeof AuthResetRoute
  '/customers/new': typeof AppCustomersNewRoute
  '/profile/change-password': typeof AppProfileChangePasswordRoute
  '/customers/': typeof AppCustomersIndexRoute
  '/profile/': typeof AppProfileIndexRoute
  '/customers/$id/edit': typeof AppCustomersIdEditRoute
  '/customers/$id/': typeof AppCustomersIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/reset': typeof AuthResetRoute
  '/customers/new': typeof AppCustomersNewRoute
  '/profile/change-password': typeof AppProfileChangePasswordRoute
  '/customers': typeof AppCustomersIndexRoute
  '/profile': typeof AppProfileIndexRoute
  '/customers/$id/edit': typeof AppCustomersIdEditRoute
  '/customers/$id': typeof AppCustomersIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/reset': typeof AuthResetRoute
  '/_app/customers/new': typeof AppCustomersNewRoute
  '/_app/profile/change-password': typeof AppProfileChangePasswordRoute
  '/_app/customers/': typeof AppCustomersIndexRoute
  '/_app/profile/': typeof AppProfileIndexRoute
  '/_app/customers/$id/edit': typeof AppCustomersIdEditRoute
  '/_app/customers/$id/': typeof AppCustomersIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/auth/forgot'
    | '/auth/reset'
    | '/customers/new'
    | '/profile/change-password'
    | '/customers/'
    | '/profile/'
    | '/customers/$id/edit'
    | '/customers/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/auth/forgot'
    | '/auth/reset'
    | '/customers/new'
    | '/profile/change-password'
    | '/customers'
    | '/profile'
    | '/customers/$id/edit'
    | '/customers/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/dashboard'
    | '/auth/forgot'
    | '/auth/reset'
    | '/_app/customers/new'
    | '/_app/profile/change-password'
    | '/_app/customers/'
    | '/_app/profile/'
    | '/_app/customers/$id/edit'
    | '/_app/customers/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset': {
      id: '/auth/reset'
      path: '/reset'
      fullPath: '/auth/reset'
      preLoaderRoute: typeof AuthResetRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot': {
      id: '/auth/forgot'
      path: '/forgot'
      fullPath: '/auth/forgot'
      preLoaderRoute: typeof AuthForgotRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile/': {
      id: '/_app/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof AppProfileIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers/': {
      id: '/_app/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof AppCustomersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile/change-password': {
      id: '/_app/profile/change-password'
      path: '/profile/change-password'
      fullPath: '/profile/change-password'
      preLoaderRoute: typeof AppProfileChangePasswordRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers/new': {
      id: '/_app/customers/new'
      path: '/customers/new'
      fullPath: '/customers/new'
      preLoaderRoute: typeof AppCustomersNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers/$id/': {
      id: '/_app/customers/$id/'
      path: '/customers/$id'
      fullPath: '/customers/$id/'
      preLoaderRoute: typeof AppCustomersIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers/$id/edit': {
      id: '/_app/customers/$id/edit'
      path: '/customers/$id/edit'
      fullPath: '/customers/$id/edit'
      preLoaderRoute: typeof AppCustomersIdEditRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppCustomersNewRoute: typeof AppCustomersNewRoute
  AppProfileChangePasswordRoute: typeof AppProfileChangePasswordRoute
  AppCustomersIndexRoute: typeof AppCustomersIndexRoute
  AppProfileIndexRoute: typeof AppProfileIndexRoute
  AppCustomersIdEditRoute: typeof AppCustomersIdEditRoute
  AppCustomersIdIndexRoute: typeof AppCustomersIdIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppCustomersNewRoute: AppCustomersNewRoute,
  AppProfileChangePasswordRoute: AppProfileChangePasswordRoute,
  AppCustomersIndexRoute: AppCustomersIndexRoute,
  AppProfileIndexRoute: AppProfileIndexRoute,
  AppCustomersIdEditRoute: AppCustomersIdEditRoute,
  AppCustomersIdIndexRoute: AppCustomersIdIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthForgotRoute: typeof AuthForgotRoute
  AuthResetRoute: typeof AuthResetRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotRoute: AuthForgotRoute,
  AuthResetRoute: AuthResetRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
