/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthResetRouteImport } from './routes/auth.reset'
import { Route as AuthForgotRouteImport } from './routes/auth.forgot'
import { Route as AppShipmentsRouteImport } from './routes/_app.shipments'
import { Route as AppReceiptsRouteImport } from './routes/_app.receipts'
import { Route as AppPurchasesRouteImport } from './routes/_app.purchases'
import { Route as AppOutstandingRouteImport } from './routes/_app.outstanding'
import { Route as AppLedgersRouteImport } from './routes/_app.ledgers'
import { Route as AppJournalRouteImport } from './routes/_app.journal'
import { Route as AppInvoicesRouteImport } from './routes/_app.invoices'
import { Route as AppExpensesRouteImport } from './routes/_app.expenses'
import { Route as AppDriversRouteImport } from './routes/_app.drivers'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppWorkOrdersIndexRouteImport } from './routes/_app.work-orders.index'
import { Route as AppVendorsIndexRouteImport } from './routes/_app.vendors.index'
import { Route as AppSettingsIndexRouteImport } from './routes/_app.settings.index'
import { Route as AppProfileIndexRouteImport } from './routes/_app.profile.index'
import { Route as AppFleetIndexRouteImport } from './routes/_app.fleet.index'
import { Route as AppCustomersIndexRouteImport } from './routes/_app.customers.index'
import { Route as AppWorkOrdersNewRouteImport } from './routes/_app.work-orders.new'
import { Route as AppVendorsNewRouteImport } from './routes/_app.vendors.new'
import { Route as AppSettingsUsersRouteImport } from './routes/_app.settings.users'
import { Route as AppSettingsRolesRouteImport } from './routes/_app.settings.roles'
import { Route as AppSettingsCompanyRouteImport } from './routes/_app.settings.company'
import { Route as AppProfileChangePasswordRouteImport } from './routes/_app.profile.change-password'
import { Route as AppFleetNewRouteImport } from './routes/_app.fleet.new'
import { Route as AppCustomersNewRouteImport } from './routes/_app.customers.new'
import { Route as AppWorkOrdersIdIndexRouteImport } from './routes/_app.work-orders.$id.index'
import { Route as AppVendorsIdIndexRouteImport } from './routes/_app.vendors.$id.index'
import { Route as AppFleetIdIndexRouteImport } from './routes/_app.fleet.$id.index'
import { Route as AppCustomersIdIndexRouteImport } from './routes/_app.customers.$id.index'
import { Route as AppWorkOrdersIdEditRouteImport } from './routes/_app.work-orders.$id.edit'
import { Route as AppVendorsIdEditRouteImport } from './routes/_app.vendors.$id.edit'
import { Route as AppFleetIdEditRouteImport } from './routes/_app.fleet.$id.edit'
import { Route as AppCustomersIdEditRouteImport } from './routes/_app.customers.$id.edit'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetRoute = AuthResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotRoute = AuthForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => AuthRoute,
} as any)
const AppShipmentsRoute = AppShipmentsRouteImport.update({
  id: '/shipments',
  path: '/shipments',
  getParentRoute: () => AppRoute,
} as any)
const AppReceiptsRoute = AppReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => AppRoute,
} as any)
const AppPurchasesRoute = AppPurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => AppRoute,
} as any)
const AppOutstandingRoute = AppOutstandingRouteImport.update({
  id: '/outstanding',
  path: '/outstanding',
  getParentRoute: () => AppRoute,
} as any)
const AppLedgersRoute = AppLedgersRouteImport.update({
  id: '/ledgers',
  path: '/ledgers',
  getParentRoute: () => AppRoute,
} as any)
const AppJournalRoute = AppJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesRoute = AppInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AppRoute,
} as any)
const AppExpensesRoute = AppExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AppRoute,
} as any)
const AppDriversRoute = AppDriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkOrdersIndexRoute = AppWorkOrdersIndexRouteImport.update({
  id: '/work-orders/',
  path: '/work-orders/',
  getParentRoute: () => AppRoute,
} as any)
const AppVendorsIndexRoute = AppVendorsIndexRouteImport.update({
  id: '/vendors/',
  path: '/vendors/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileIndexRoute = AppProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => AppRoute,
} as any)
const AppFleetIndexRoute = AppFleetIndexRouteImport.update({
  id: '/fleet/',
  path: '/fleet/',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersIndexRoute = AppCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkOrdersNewRoute = AppWorkOrdersNewRouteImport.update({
  id: '/work-orders/new',
  path: '/work-orders/new',
  getParentRoute: () => AppRoute,
} as any)
const AppVendorsNewRoute = AppVendorsNewRouteImport.update({
  id: '/vendors/new',
  path: '/vendors/new',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsUsersRoute = AppSettingsUsersRouteImport.update({
  id: '/settings/users',
  path: '/settings/users',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRolesRoute = AppSettingsRolesRouteImport.update({
  id: '/settings/roles',
  path: '/settings/roles',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsCompanyRoute = AppSettingsCompanyRouteImport.update({
  id: '/settings/company',
  path: '/settings/company',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileChangePasswordRoute =
  AppProfileChangePasswordRouteImport.update({
    id: '/profile/change-password',
    path: '/profile/change-password',
    getParentRoute: () => AppRoute,
  } as any)
const AppFleetNewRoute = AppFleetNewRouteImport.update({
  id: '/fleet/new',
  path: '/fleet/new',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersNewRoute = AppCustomersNewRouteImport.update({
  id: '/customers/new',
  path: '/customers/new',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkOrdersIdIndexRoute = AppWorkOrdersIdIndexRouteImport.update({
  id: '/work-orders/$id/',
  path: '/work-orders/$id/',
  getParentRoute: () => AppRoute,
} as any)
const AppVendorsIdIndexRoute = AppVendorsIdIndexRouteImport.update({
  id: '/vendors/$id/',
  path: '/vendors/$id/',
  getParentRoute: () => AppRoute,
} as any)
const AppFleetIdIndexRoute = AppFleetIdIndexRouteImport.update({
  id: '/fleet/$id/',
  path: '/fleet/$id/',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersIdIndexRoute = AppCustomersIdIndexRouteImport.update({
  id: '/customers/$id/',
  path: '/customers/$id/',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkOrdersIdEditRoute = AppWorkOrdersIdEditRouteImport.update({
  id: '/work-orders/$id/edit',
  path: '/work-orders/$id/edit',
  getParentRoute: () => AppRoute,
} as any)
const AppVendorsIdEditRoute = AppVendorsIdEditRouteImport.update({
  id: '/vendors/$id/edit',
  path: '/vendors/$id/edit',
  getParentRoute: () => AppRoute,
} as any)
const AppFleetIdEditRoute = AppFleetIdEditRouteImport.update({
  id: '/fleet/$id/edit',
  path: '/fleet/$id/edit',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersIdEditRoute = AppCustomersIdEditRouteImport.update({
  id: '/customers/$id/edit',
  path: '/customers/$id/edit',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/drivers': typeof AppDriversRoute
  '/expenses': typeof AppExpensesRoute
  '/invoices': typeof AppInvoicesRoute
  '/journal': typeof AppJournalRoute
  '/ledgers': typeof AppLedgersRoute
  '/outstanding': typeof AppOutstandingRoute
  '/purchases': typeof AppPurchasesRoute
  '/receipts': typeof AppReceiptsRoute
  '/shipments': typeof AppShipmentsRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/reset': typeof AuthResetRoute
  '/customers/new': typeof AppCustomersNewRoute
  '/fleet/new': typeof AppFleetNewRoute
  '/profile/change-password': typeof AppProfileChangePasswordRoute
  '/settings/company': typeof AppSettingsCompanyRoute
  '/settings/roles': typeof AppSettingsRolesRoute
  '/settings/users': typeof AppSettingsUsersRoute
  '/vendors/new': typeof AppVendorsNewRoute
  '/work-orders/new': typeof AppWorkOrdersNewRoute
  '/customers/': typeof AppCustomersIndexRoute
  '/fleet/': typeof AppFleetIndexRoute
  '/profile/': typeof AppProfileIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/vendors/': typeof AppVendorsIndexRoute
  '/work-orders/': typeof AppWorkOrdersIndexRoute
  '/customers/$id/edit': typeof AppCustomersIdEditRoute
  '/fleet/$id/edit': typeof AppFleetIdEditRoute
  '/vendors/$id/edit': typeof AppVendorsIdEditRoute
  '/work-orders/$id/edit': typeof AppWorkOrdersIdEditRoute
  '/customers/$id/': typeof AppCustomersIdIndexRoute
  '/fleet/$id/': typeof AppFleetIdIndexRoute
  '/vendors/$id/': typeof AppVendorsIdIndexRoute
  '/work-orders/$id/': typeof AppWorkOrdersIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/drivers': typeof AppDriversRoute
  '/expenses': typeof AppExpensesRoute
  '/invoices': typeof AppInvoicesRoute
  '/journal': typeof AppJournalRoute
  '/ledgers': typeof AppLedgersRoute
  '/outstanding': typeof AppOutstandingRoute
  '/purchases': typeof AppPurchasesRoute
  '/receipts': typeof AppReceiptsRoute
  '/shipments': typeof AppShipmentsRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/reset': typeof AuthResetRoute
  '/customers/new': typeof AppCustomersNewRoute
  '/fleet/new': typeof AppFleetNewRoute
  '/profile/change-password': typeof AppProfileChangePasswordRoute
  '/settings/company': typeof AppSettingsCompanyRoute
  '/settings/roles': typeof AppSettingsRolesRoute
  '/settings/users': typeof AppSettingsUsersRoute
  '/vendors/new': typeof AppVendorsNewRoute
  '/work-orders/new': typeof AppWorkOrdersNewRoute
  '/customers': typeof AppCustomersIndexRoute
  '/fleet': typeof AppFleetIndexRoute
  '/profile': typeof AppProfileIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/vendors': typeof AppVendorsIndexRoute
  '/work-orders': typeof AppWorkOrdersIndexRoute
  '/customers/$id/edit': typeof AppCustomersIdEditRoute
  '/fleet/$id/edit': typeof AppFleetIdEditRoute
  '/vendors/$id/edit': typeof AppVendorsIdEditRoute
  '/work-orders/$id/edit': typeof AppWorkOrdersIdEditRoute
  '/customers/$id': typeof AppCustomersIdIndexRoute
  '/fleet/$id': typeof AppFleetIdIndexRoute
  '/vendors/$id': typeof AppVendorsIdIndexRoute
  '/work-orders/$id': typeof AppWorkOrdersIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/drivers': typeof AppDriversRoute
  '/_app/expenses': typeof AppExpensesRoute
  '/_app/invoices': typeof AppInvoicesRoute
  '/_app/journal': typeof AppJournalRoute
  '/_app/ledgers': typeof AppLedgersRoute
  '/_app/outstanding': typeof AppOutstandingRoute
  '/_app/purchases': typeof AppPurchasesRoute
  '/_app/receipts': typeof AppReceiptsRoute
  '/_app/shipments': typeof AppShipmentsRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/reset': typeof AuthResetRoute
  '/_app/customers/new': typeof AppCustomersNewRoute
  '/_app/fleet/new': typeof AppFleetNewRoute
  '/_app/profile/change-password': typeof AppProfileChangePasswordRoute
  '/_app/settings/company': typeof AppSettingsCompanyRoute
  '/_app/settings/roles': typeof AppSettingsRolesRoute
  '/_app/settings/users': typeof AppSettingsUsersRoute
  '/_app/vendors/new': typeof AppVendorsNewRoute
  '/_app/work-orders/new': typeof AppWorkOrdersNewRoute
  '/_app/customers/': typeof AppCustomersIndexRoute
  '/_app/fleet/': typeof AppFleetIndexRoute
  '/_app/profile/': typeof AppProfileIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/vendors/': typeof AppVendorsIndexRoute
  '/_app/work-orders/': typeof AppWorkOrdersIndexRoute
  '/_app/customers/$id/edit': typeof AppCustomersIdEditRoute
  '/_app/fleet/$id/edit': typeof AppFleetIdEditRoute
  '/_app/vendors/$id/edit': typeof AppVendorsIdEditRoute
  '/_app/work-orders/$id/edit': typeof AppWorkOrdersIdEditRoute
  '/_app/customers/$id/': typeof AppCustomersIdIndexRoute
  '/_app/fleet/$id/': typeof AppFleetIdIndexRoute
  '/_app/vendors/$id/': typeof AppVendorsIdIndexRoute
  '/_app/work-orders/$id/': typeof AppWorkOrdersIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/drivers'
    | '/expenses'
    | '/invoices'
    | '/journal'
    | '/ledgers'
    | '/outstanding'
    | '/purchases'
    | '/receipts'
    | '/shipments'
    | '/auth/forgot'
    | '/auth/reset'
    | '/customers/new'
    | '/fleet/new'
    | '/profile/change-password'
    | '/settings/company'
    | '/settings/roles'
    | '/settings/users'
    | '/vendors/new'
    | '/work-orders/new'
    | '/customers/'
    | '/fleet/'
    | '/profile/'
    | '/settings/'
    | '/vendors/'
    | '/work-orders/'
    | '/customers/$id/edit'
    | '/fleet/$id/edit'
    | '/vendors/$id/edit'
    | '/work-orders/$id/edit'
    | '/customers/$id/'
    | '/fleet/$id/'
    | '/vendors/$id/'
    | '/work-orders/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/drivers'
    | '/expenses'
    | '/invoices'
    | '/journal'
    | '/ledgers'
    | '/outstanding'
    | '/purchases'
    | '/receipts'
    | '/shipments'
    | '/auth/forgot'
    | '/auth/reset'
    | '/customers/new'
    | '/fleet/new'
    | '/profile/change-password'
    | '/settings/company'
    | '/settings/roles'
    | '/settings/users'
    | '/vendors/new'
    | '/work-orders/new'
    | '/customers'
    | '/fleet'
    | '/profile'
    | '/settings'
    | '/vendors'
    | '/work-orders'
    | '/customers/$id/edit'
    | '/fleet/$id/edit'
    | '/vendors/$id/edit'
    | '/work-orders/$id/edit'
    | '/customers/$id'
    | '/fleet/$id'
    | '/vendors/$id'
    | '/work-orders/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/dashboard'
    | '/_app/drivers'
    | '/_app/expenses'
    | '/_app/invoices'
    | '/_app/journal'
    | '/_app/ledgers'
    | '/_app/outstanding'
    | '/_app/purchases'
    | '/_app/receipts'
    | '/_app/shipments'
    | '/auth/forgot'
    | '/auth/reset'
    | '/_app/customers/new'
    | '/_app/fleet/new'
    | '/_app/profile/change-password'
    | '/_app/settings/company'
    | '/_app/settings/roles'
    | '/_app/settings/users'
    | '/_app/vendors/new'
    | '/_app/work-orders/new'
    | '/_app/customers/'
    | '/_app/fleet/'
    | '/_app/profile/'
    | '/_app/settings/'
    | '/_app/vendors/'
    | '/_app/work-orders/'
    | '/_app/customers/$id/edit'
    | '/_app/fleet/$id/edit'
    | '/_app/vendors/$id/edit'
    | '/_app/work-orders/$id/edit'
    | '/_app/customers/$id/'
    | '/_app/fleet/$id/'
    | '/_app/vendors/$id/'
    | '/_app/work-orders/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset': {
      id: '/auth/reset'
      path: '/reset'
      fullPath: '/auth/reset'
      preLoaderRoute: typeof AuthResetRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot': {
      id: '/auth/forgot'
      path: '/forgot'
      fullPath: '/auth/forgot'
      preLoaderRoute: typeof AuthForgotRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/shipments': {
      id: '/_app/shipments'
      path: '/shipments'
      fullPath: '/shipments'
      preLoaderRoute: typeof AppShipmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/receipts': {
      id: '/_app/receipts'
      path: '/receipts'
      fullPath: '/receipts'
      preLoaderRoute: typeof AppReceiptsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/purchases': {
      id: '/_app/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof AppPurchasesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/outstanding': {
      id: '/_app/outstanding'
      path: '/outstanding'
      fullPath: '/outstanding'
      preLoaderRoute: typeof AppOutstandingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ledgers': {
      id: '/_app/ledgers'
      path: '/ledgers'
      fullPath: '/ledgers'
      preLoaderRoute: typeof AppLedgersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/journal': {
      id: '/_app/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof AppJournalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoices': {
      id: '/_app/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AppInvoicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/expenses': {
      id: '/_app/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AppExpensesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/drivers': {
      id: '/_app/drivers'
      path: '/drivers'
      fullPath: '/drivers'
      preLoaderRoute: typeof AppDriversRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/work-orders/': {
      id: '/_app/work-orders/'
      path: '/work-orders'
      fullPath: '/work-orders/'
      preLoaderRoute: typeof AppWorkOrdersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vendors/': {
      id: '/_app/vendors/'
      path: '/vendors'
      fullPath: '/vendors/'
      preLoaderRoute: typeof AppVendorsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile/': {
      id: '/_app/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof AppProfileIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fleet/': {
      id: '/_app/fleet/'
      path: '/fleet'
      fullPath: '/fleet/'
      preLoaderRoute: typeof AppFleetIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers/': {
      id: '/_app/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof AppCustomersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/work-orders/new': {
      id: '/_app/work-orders/new'
      path: '/work-orders/new'
      fullPath: '/work-orders/new'
      preLoaderRoute: typeof AppWorkOrdersNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vendors/new': {
      id: '/_app/vendors/new'
      path: '/vendors/new'
      fullPath: '/vendors/new'
      preLoaderRoute: typeof AppVendorsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/users': {
      id: '/_app/settings/users'
      path: '/settings/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof AppSettingsUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/roles': {
      id: '/_app/settings/roles'
      path: '/settings/roles'
      fullPath: '/settings/roles'
      preLoaderRoute: typeof AppSettingsRolesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/company': {
      id: '/_app/settings/company'
      path: '/settings/company'
      fullPath: '/settings/company'
      preLoaderRoute: typeof AppSettingsCompanyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile/change-password': {
      id: '/_app/profile/change-password'
      path: '/profile/change-password'
      fullPath: '/profile/change-password'
      preLoaderRoute: typeof AppProfileChangePasswordRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fleet/new': {
      id: '/_app/fleet/new'
      path: '/fleet/new'
      fullPath: '/fleet/new'
      preLoaderRoute: typeof AppFleetNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers/new': {
      id: '/_app/customers/new'
      path: '/customers/new'
      fullPath: '/customers/new'
      preLoaderRoute: typeof AppCustomersNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/work-orders/$id/': {
      id: '/_app/work-orders/$id/'
      path: '/work-orders/$id'
      fullPath: '/work-orders/$id/'
      preLoaderRoute: typeof AppWorkOrdersIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vendors/$id/': {
      id: '/_app/vendors/$id/'
      path: '/vendors/$id'
      fullPath: '/vendors/$id/'
      preLoaderRoute: typeof AppVendorsIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fleet/$id/': {
      id: '/_app/fleet/$id/'
      path: '/fleet/$id'
      fullPath: '/fleet/$id/'
      preLoaderRoute: typeof AppFleetIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers/$id/': {
      id: '/_app/customers/$id/'
      path: '/customers/$id'
      fullPath: '/customers/$id/'
      preLoaderRoute: typeof AppCustomersIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/work-orders/$id/edit': {
      id: '/_app/work-orders/$id/edit'
      path: '/work-orders/$id/edit'
      fullPath: '/work-orders/$id/edit'
      preLoaderRoute: typeof AppWorkOrdersIdEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vendors/$id/edit': {
      id: '/_app/vendors/$id/edit'
      path: '/vendors/$id/edit'
      fullPath: '/vendors/$id/edit'
      preLoaderRoute: typeof AppVendorsIdEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fleet/$id/edit': {
      id: '/_app/fleet/$id/edit'
      path: '/fleet/$id/edit'
      fullPath: '/fleet/$id/edit'
      preLoaderRoute: typeof AppFleetIdEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers/$id/edit': {
      id: '/_app/customers/$id/edit'
      path: '/customers/$id/edit'
      fullPath: '/customers/$id/edit'
      preLoaderRoute: typeof AppCustomersIdEditRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppDriversRoute: typeof AppDriversRoute
  AppExpensesRoute: typeof AppExpensesRoute
  AppInvoicesRoute: typeof AppInvoicesRoute
  AppJournalRoute: typeof AppJournalRoute
  AppLedgersRoute: typeof AppLedgersRoute
  AppOutstandingRoute: typeof AppOutstandingRoute
  AppPurchasesRoute: typeof AppPurchasesRoute
  AppReceiptsRoute: typeof AppReceiptsRoute
  AppShipmentsRoute: typeof AppShipmentsRoute
  AppCustomersNewRoute: typeof AppCustomersNewRoute
  AppFleetNewRoute: typeof AppFleetNewRoute
  AppProfileChangePasswordRoute: typeof AppProfileChangePasswordRoute
  AppSettingsCompanyRoute: typeof AppSettingsCompanyRoute
  AppSettingsRolesRoute: typeof AppSettingsRolesRoute
  AppSettingsUsersRoute: typeof AppSettingsUsersRoute
  AppVendorsNewRoute: typeof AppVendorsNewRoute
  AppWorkOrdersNewRoute: typeof AppWorkOrdersNewRoute
  AppCustomersIndexRoute: typeof AppCustomersIndexRoute
  AppFleetIndexRoute: typeof AppFleetIndexRoute
  AppProfileIndexRoute: typeof AppProfileIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
  AppVendorsIndexRoute: typeof AppVendorsIndexRoute
  AppWorkOrdersIndexRoute: typeof AppWorkOrdersIndexRoute
  AppCustomersIdEditRoute: typeof AppCustomersIdEditRoute
  AppFleetIdEditRoute: typeof AppFleetIdEditRoute
  AppVendorsIdEditRoute: typeof AppVendorsIdEditRoute
  AppWorkOrdersIdEditRoute: typeof AppWorkOrdersIdEditRoute
  AppCustomersIdIndexRoute: typeof AppCustomersIdIndexRoute
  AppFleetIdIndexRoute: typeof AppFleetIdIndexRoute
  AppVendorsIdIndexRoute: typeof AppVendorsIdIndexRoute
  AppWorkOrdersIdIndexRoute: typeof AppWorkOrdersIdIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppDriversRoute: AppDriversRoute,
  AppExpensesRoute: AppExpensesRoute,
  AppInvoicesRoute: AppInvoicesRoute,
  AppJournalRoute: AppJournalRoute,
  AppLedgersRoute: AppLedgersRoute,
  AppOutstandingRoute: AppOutstandingRoute,
  AppPurchasesRoute: AppPurchasesRoute,
  AppReceiptsRoute: AppReceiptsRoute,
  AppShipmentsRoute: AppShipmentsRoute,
  AppCustomersNewRoute: AppCustomersNewRoute,
  AppFleetNewRoute: AppFleetNewRoute,
  AppProfileChangePasswordRoute: AppProfileChangePasswordRoute,
  AppSettingsCompanyRoute: AppSettingsCompanyRoute,
  AppSettingsRolesRoute: AppSettingsRolesRoute,
  AppSettingsUsersRoute: AppSettingsUsersRoute,
  AppVendorsNewRoute: AppVendorsNewRoute,
  AppWorkOrdersNewRoute: AppWorkOrdersNewRoute,
  AppCustomersIndexRoute: AppCustomersIndexRoute,
  AppFleetIndexRoute: AppFleetIndexRoute,
  AppProfileIndexRoute: AppProfileIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
  AppVendorsIndexRoute: AppVendorsIndexRoute,
  AppWorkOrdersIndexRoute: AppWorkOrdersIndexRoute,
  AppCustomersIdEditRoute: AppCustomersIdEditRoute,
  AppFleetIdEditRoute: AppFleetIdEditRoute,
  AppVendorsIdEditRoute: AppVendorsIdEditRoute,
  AppWorkOrdersIdEditRoute: AppWorkOrdersIdEditRoute,
  AppCustomersIdIndexRoute: AppCustomersIdIndexRoute,
  AppFleetIdIndexRoute: AppFleetIdIndexRoute,
  AppVendorsIdIndexRoute: AppVendorsIdIndexRoute,
  AppWorkOrdersIdIndexRoute: AppWorkOrdersIdIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthForgotRoute: typeof AuthForgotRoute
  AuthResetRoute: typeof AuthResetRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotRoute: AuthForgotRoute,
  AuthResetRoute: AuthResetRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
